name: Windows Build & Release

on:
  push:
    branches:
      - master
      - main
      - ztonecloud-theme-win64-v1
  pull_request:
    branches:
      - master
      - main
      - ztonecloud-theme-win64-v1
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      APP_NAME: ZTOneCloudDISK
      APP_VERSION: V1.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC and dependencies
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt (6.5.3) and CMake
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: 'windows'
          arch: 'win64_msvc2019_64'
          tools: 'tools_cmake'

      - name: Install NSIS (for installer)
        run: choco install nsis -y

      - name: Install pkg-config
        run: choco install pkgconfiglite -y

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install zlib with vcpkg
        run: .\vcpkg\vcpkg.exe install zlib:x64-windows

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build project
        run: |
          cd build
          cmake --build . --config Release

      # 其他打包步骤可根据需求继续添加
